### ISSUE TITLE
Login with basic auth token

### ISSUE THREAD

**Issue by 5knnbdwm** [jazzband/dj-rest-auth#104]
I'm using a Postman to test my API endpoints but sadly can use it to login as Postman creates a Basic auth token. Is there a way that dj-rest-auth in the login API accepts the token?

Have the same configuration as the demo project

**Comment by Reston** [comment]
I had the same doubt but i'm working with Insomnia

What I did was to create in the enviroment a new variable "jwt_token" with a "Response => Body Attribute"

![Screenshot from 2021-10-20 14-41-33](https://user-images.githubusercontent.com/1129238/138143865-7717de9a-8837-46f8-b1e9-da1c194e2804.png)

This allows to do a prefetch of the token that you'll need for the any request.
So I call the POST method /auth/login/ with its parameters previously written.
Then filter the response to get the $.access_token

![Screenshot from 2021-10-20 14-40-08](https://user-images.githubusercontent.com/1129238/138143747-93023417-d2de-428c-9d33-b074d0a22865.png)


At the end you'll request will look something like this.


![Screenshot from 2021-10-20 14-42-53](https://user-images.githubusercontent.com/1129238/138144099-c90324a5-5a4b-40eb-96db-54a19b1e6f80.png)
