### ISSUE TITLE
JWT_TOKEN_CLAIMS_SERIALIZER is not being read from the REST_AUTH_SERIALIZERS dict

### ISSUE THREAD

**Issue by adriangzz** [jazzband/dj-rest-auth#106]
Adding JWT_TOKEN_CLAIMS_SERIALIZER  to REST_AUTH_SERIALIZERS dictionary in settings.py will not replace the serializer.

The error is in jwt_encode function inside utils.py, the import is being done with `import_callable(getattr(settings, 'JWT_TOKEN_CLAIMS_SERIALIZER', TokenObtainPairSerializer))`, grabbing it directly from settings and not from the REST_AUTH_SERIALIZERS dict.

I will create a pull request soon :)

**Comment by adriangzz** [comment]
Address issue #107

**Comment by iMerica** [comment]
Closing this since it was addressed. Thank you.
