### ISSUE TITLE
Password Change not working on API request.

### ISSUE THREAD

**Issue by RajeshJ3** [jazzband/dj-rest-auth#112]
When I am using the browser to **change the password** at `http://127.0.0.1:8000/auth/password/change/` it's working fine.

![Screenshot from 2020-07-10 18-00-05](https://user-images.githubusercontent.com/41537758/87154653-3881a880-c2d7-11ea-8d94-b05c1eb63d86.png)

But, When I use Postman for the same, it's throwing error **Authentication credentials were not provided.**.

```json
{
    "detail": "Authentication credentials were not provided."
}
```
![Screenshot from 2020-07-10 17-56-17](https://user-images.githubusercontent.com/41537758/87154560-15ef8f80-c2d7-11ea-8f01-89345a57195c.png)

**I am using -**
Python               3.8.2
Django               3.0.8
pip                      20.0.2
dj-rest-auth        1.0.9

Any help on this will be appreciated
Thank you 😇

**Comment by iMerica** [comment]
Do you have a way of exporting the request to curl? If so, lets see that. The issue could be other values in the request not shown in the image you provided.

**Comment by RajeshJ3** [comment]
Thanks for your quick response @iMerica 

Here's the atteched screenshot of the curl request.

![Screenshot from 2020-07-10 18-58-24](https://user-images.githubusercontent.com/41537758/87159715-666aeb00-c2df-11ea-82e5-f6997b65f312.png)

**Comment by iMerica** [comment]
Try adding content-type and accept type headers with `application/json`

**Comment by iMerica** [comment]
Also thats not a valid payload for the endpoint. This library (dj-rest-auth) extends Django Rest Framework, which is focused on REST and JSON. I'm going to close this for now, since the tests are all passing and it appears to be a client issue.
