### ISSUE TITLE
documentation angular app demo link broken 

### ISSUE THREAD

**Issue by yooyoyo** [jazzband/dj-rest-auth#121]
**Angular app**

iMerica has also created angular module which uses API endpoints from this app - angular-django-registration-auth

this is the provided link - https://github.com/iMerica/angular-django-registration-auth
and it seems to be broken..
also can u provide more details as to how we can integrate out front end like react or angular with dj-rest-auth. Any related article link or advice will help.

**Comment by iMerica** [comment]
Thanks 👍  - I just pushed a fix.
