### ISSUE TITLE
Is the http cookie storing the correct token?

### ISSUE THREAD

**Issue by TutoringSprint** [jazzband/dj-rest-auth#123]
On a successful login request the http cookie stored is the access token and not the refresh token, is this intended?

**Comment by iMerica** [comment]
Yes it's intended. I'm going to close this ticket, but feel free to create a bug if you can describe a defect.

**Comment by kevinxh** [comment]
curious if anyone know, where do you store the refresh_token if it's not in the httponly cookie?
