### ISSUE TITLE
Login with username or email for an account

### ISSUE THREAD

**Issue by SRomero321** [jazzband/dj-rest-auth#126]
Hi all,

Is it possible to configure dj-rest-auth to allow login by username or email for one account? For example:

username/password or email/password?

Thanks,
Steven

**Comment by iMerica** [comment]
Yes it's possible. Have a look at the Django All Auth configuration for more details on enabling that (see `ACCOUNT_AUTHENTICATION_METHOD`)

https://django-allauth.readthedocs.io/en/latest/configuration.html

**Comment by SRomero321** [comment]
iMerica,

Would enabling Django All Auth change the Django Schema in our database, or be disruptive to our current accounts, or is it a seamless transition from base dj-rest-auth?

Thanks,

Steve

**Comment by iMerica** [comment]
All auth has it's own models and a small amount of migrations. If your deployment process already runs migrations automatically it should be seamless. YMMV.
