### ISSUE TITLE
Password Reset Email not being sent?

### ISSUE THREAD

**Issue by anatolzak** [jazzband/dj-rest-auth#127]
Hi!

Just wanted to say, thanks for mainting this project! 🙂

I submited a POST request to `/dj-rest-auth/password/reset/` and I got:
```json
{
    "detail": "Password reset e-mail has been sent."
}
```

But for some reason, I don't see the email in my console...

I am using `EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'` in `settings.py`

I am running it during development, can that be the reason it doesn't "send" the email?

**Comment by iMerica** [comment]
Hi @anatolzak. The password feature just uses the `PasswordResetForm` class from Django for handling email. 

I think it could be an issue with your development environment. To confirm, you can override `PASSWORD_RESET_SERIALIZER` with a class that extends `PasswordResetSerializer` and debug from there.

**Comment by stfenjobs** [comment]
hi   @anatolzak 

me too , i have  the error too

do you know how to fixed it ?

**Comment by anatolzak** [comment]
Hi @stfenjobs,

When I looked into it, I realized there was no error. I was requesting the reset password email for an email address that didn't exist so that's why it didn't send the email. You need to create a user and then try to use their email address to test the reset password email API endpoint.

**Comment by stfenjobs** [comment]
i fixed it

when i custom PasswordResetSerializer, it can't send email

because  i forgot add the code  `password_reset_form_class = ResetPasswordForm`

full code(can work):

```
from allauth.account.forms import ResetPasswordForm

class MyPasswordResetSerializer(PasswordResetSerializer):
    password_reset_form_class = ResetPasswordForm

   # some code ...

```

because it use django ResetPasswordForm by default, but  not allauth ResetPasswordForm

**Comment by stfenjobs** [comment]
i know why it  can't send email  https://github.com/Tivix/django-rest-auth/issues/388#issuecomment-350174237
