### ISSUE TITLE
What's the Age of the Access Token and Refresh Token and Can I change it?

### ISSUE THREAD

**Issue by anatolzak** [jazzband/dj-rest-auth#128]
Hi!

I was trying to look at the docs but wasn't able to find anywhere mentioning the age of the access token and refresh token.

Also, can I change their age?

Thanks so much!
Anatol

**Comment by kylenguyen1014** [comment]
@anatolzak dj-rest-auth doesn't handle JWT settings, by default access token lives for 5mins and refresh token lives for 1 day. Check [djangorestframework-simplejwt](https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html) for more info. 
You would want to add something like this in your settings.py 
`# Django project settings.py

from datetime import timedelta

...

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5), #change this value to whatever you want it to last
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
   ...
}`
