### ISSUE TITLE
Enable the dependency graph for this repo

### ISSUE THREAD

**Issue by mohmyo** [jazzband/dj-rest-auth#131]
It will be a useful thing to see in the insights tab.

https://docs.github.com/en/github/visualizing-repository-data-with-graphs/about-the-dependency-graph#enabling-the-dependency-graph

**Comment by iMerica** [comment]
@jezdez Is this something you can help with? I don't see the option myself.

**Comment by mohmyo** [comment]
dependency graph is not enabled till now

**Comment by jezdez** [comment]
Done! Sorry for the delay.

**Comment by mohmyo** [comment]
No problem, thank you!
