### ISSUE TITLE
Send a boolean in response indicating signup or login

### ISSUE THREAD

**Issue by aryan9600** [jazzband/dj-rest-auth#137]
It would be really helpful if there was a way to know if the user is logging in for the first time, or is a recurring user while using any social login view. I was thinking of maybe a boolean value in the response along with the key, which indicates if the user is logging in for the first time. Is there any way to do this currently?

**Comment by iMerica** [comment]
You can override the login serializer with your own and do some calculation between "date_joined" and the "last_login" to determine if a user is logging in for the first time.

https://dj-rest-auth.readthedocs.io/en/latest/configuration.html
