### ISSUE TITLE
PasswordChangeSerializer does not confirm submitted password is correct

### ISSUE THREAD

**Issue by zach-watrhub** [jazzband/dj-rest-auth#14]
During a QA pass of integrating `dj-rest-auth`, I noticed that I could change my password if I submitted a request with valid session/csrf info yet provided an incorrect password.

In reading the relevant serializer [this function](https://github.com/jazzband/dj-rest-auth/blob/master/dj_rest_auth/serializers.py#L248) - never appears to be called and seems to be related to exactly this behaviour.

I want to check that I am understanding things correctly before attempting to write a PR to include it.

--------

Ah - it appears that I may have been missing setting `OLD_PASSWORD_FIELD_ENABLED`.

**Comment by iMerica** [comment]
It sounds like this issue can be closed then. Let us know if anything else comes up.
