### ISSUE TITLE
how to login with allauth?

### ISSUE THREAD

**Issue by jinserk** [jazzband/dj-rest-auth#144]
Hi,

I'm a newbie on OAuth2, and I'm trying to connect `dj_rest_auth` to `allauth`, as described in the official docs, but still don't know how to login from Google. When I set up my settings, `dj_rest_auth/google/` shows an api page with the POST with two `access token` and `code` input forms, but I'd like to use the login page as `accounts/google/login` with `allauth` setting. Of course, this login from `accounts/google/login` doesn't affect the api authentication. 
I had a lot of googling but couldn't find any proper howto for this. Can you give a clue to achieve this?

Thank you so much!

**Comment by martimarkov** [comment]
@jinserk Have you managed to solve the google login?

**Comment by devNULLrebooted** [comment]
Hi Jinserk,
I had the same issue. 
I found that the best way to realize this is using the GoogleOAuth2Adapter in a SocialLoginView:
```
from allauth.socialaccount.providers.google.views import GoogleOAuth2Adapter
from dj_rest_auth.registration.views import SocialLoginView

class GoogleLogin(SocialLoginView):
    adapter_class = GoogleOAuth2Adapter
```
Hope it will help you and the community.
Let me know if you need more help.

Fred
