### ISSUE TITLE
custom UserDetailsSerializer can't support UserProfile

### ISSUE THREAD

**Issue by stfenjobs** [jazzband/dj-rest-auth#146]
django: 3.1.1   
dj-rest-auth: 1.1.1

# models.py
```
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    is_ok = models.BooleanField("是否is_ok", default=False) 
```
  
# settings:
```
REST_AUTH_SERIALIZERS ={
    "USER_DETAILS_SERIALIZER":"xx.apps.xxx.serializers.UserDetailsSerializer", 
}
```

# serializers.py
```
class UserDetailsSerializer(UserDetailsSerializer):
    class Meta:
        model = UserProfile
        fields = ('is_ok',)
```

then i open **http://0.0.0.0:8000/rest-auth/user/**

i got :

![image](https://user-images.githubusercontent.com/6580897/93468821-28fb8d00-f922-11ea-92d0-abb73497cfc6.png)

i can't got **is_ok**

**Comment by iMerica** [comment]
Create a model serializer for the User model and add a method field. Example: https://stackoverflow.com/a/39489034/1118492.

**Comment by iMerica** [comment]
This is not related to this package, so I'm going to close this issue for now
