### ISSUE TITLE
REST_AUTH_REGISTER_PERMISSION_CLASSES not working as expected

### ISSUE THREAD

**Issue by fschneider-wedge** [jazzband/dj-rest-auth#151]
Hi

In my project, my front application accesses my api via an api key. For the registration of new users I therefore need the api registration to have permission `IsAuthenticated`. 

So, I've followed documentation by adding in my settings file:
```python
REST_AUTH_REGISTER_PERMISSION_CLASSES = ("rest_framework.permissions.IsAuthenticated",)
```
But api failed with `str(28) "'str' object is not callable"`. Indeed, `dj_rest_auth/registration/app_settings.py` append 
`permission_classes` directly with the string `"rest_framework.permissions.IsAuthenticated"` where It should be the class.

So to make it works, I've should update my settings like this:
```python
from rest_framework import permissions
REST_AUTH_REGISTER_PERMISSION_CLASSES = (permissions.IsAuthenticated,)
```

May the documentation or code should be modified to be consistent ?

**Comment by mohmyo** [comment]
Thanks for raising this issue.

@iMerica I think the fix in https://github.com/jazzband/dj-rest-auth/pull/130 isn't included in a release yet, we should include it and update the docs also for this version.

**Comment by iMerica** [comment]
I just cut a new release. 1.1.2 should fix this.

**Comment by soojiinleee** [comment]
Tanks a ton!! I've solved the same issue very easily!
