### ISSUE TITLE
Suggestion: Use different status code for login failure when email is not verified

### ISSUE THREAD

**Issue by Hafnernuss** [jazzband/dj-rest-auth#153]
Hi,

When a user tries to login with invalid credentials, a response with status `400: BAD REQUEST` is returned. This is perfectly fine. However, if the credentials are correct but the used email is not verified, the same status is returned. This makes it kind of hard to distinguish errors in frontends, even more so if localization is used. What about another status code? Maybe 403? Maybe configurable?

**Comment by iMerica** [comment]
I think 400 is the best available response code for that scenario, but the response body should include some context about the reasoning.

**Comment by Hafnernuss** [comment]
How could this work? For now i have written my own exception handler that checks if the passed text is indeed matching `email is not verified` and change the status code to 403. This is extremly hacky and I definitly would prefer another option ;)

**Comment by iMerica** [comment]
Why do you consider that to be hacky? Overriding views & serializers in this package is a normal thing in this package and many others in the Django/DRF ecosystem. Otherwise packages like this one become extremely messy by trying to cater to every possible edge case.

**Comment by Hafnernuss** [comment]
It just feels wrong to provide an exception handler that catches all exceptions just to match one by it's string value ;)
But I totally agree, overriding things is a core principle of DRF and I agree that this package can't accomodate every wish/feature, I just thought it could be something that maybe more people need.

**Comment by jerinpetergeorge** [comment]
Usually, we override the corresponding method to get the desired results. But, here, the method [**`LoginSerializer.validate(...)`**](https://github.com/jazzband/dj-rest-auth/blob/7986184821bbe6a64b31117af1435e91212971ec/dj_rest_auth/serializers.py#L64) seems bulky and *hard* to override.

So, I have a few suggestions,
1. Create settings variable for status codes as well as the error messages
2. Decouple the `validate()` method by splitting the functionality across multiple methods and thus the developer can override the function easily.

What do you think? @iMerica @Hafnernuss

**Comment by Hafnernuss** [comment]
I initially planned on overriding this method, and I choose not to, exactly because of the bulkiness.  Personally I'd go for your first suggestion as it adds more flexibility overall, though it might be more work.

**Comment by jerinpetergeorge** [comment]
I tried to shrink the size of the `validate(...)` method in #170 and it seems all tests are passing.

Now, we can override any of the *single responsibility method* to get the desired behavior. 

Suggestions are highly appreciated!!!
