### ISSUE TITLE
Email verification is not enforced. Disregarding ACCOUNT_EMAIL_VERIFICATION setting

### ISSUE THREAD

**Issue by florianmartens** [jazzband/dj-rest-auth#156]
I'm using two packages to assist me with authentication. One is js_rest_auth and the other one is allauth.

The latter has a setting to require users to validate their email addresses before a login is possible. I'm setting ACCOUNT_EMAIL_VERIFICATION = "mandatory" but it has no effect. My relevant settings look as follows:

```
INSTALLED_APPS = [
    ...
    "django.contrib.sites",
    "rest_framework.authtoken",
    "allauth.account",
    "allauth.account",
    "allauth.socialaccount",
    "dj_rest_auth",
    ....
]
```

```
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 90
ACCOUNT_USER_MODEL_EMAIL_FIELD = "email"
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_REQUIRED=True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED=False
ACCOUNT_USER_MODEL_USERNAME_FIELD = "email"
ACCOUNT_PRESERVE_USERNAME_CASING = False
ACCOUNT_ADAPTER = "users.accountadapter.CustomAccountAdapter"
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

```
```
REST_FRAMEWORK = {
    ....
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ]
}
```
The users I create aren't verified (verified attribute an Email Address Model) but are created with is_active=True. When I send a login request for a non-verified user, a valid token is issued.

**Edit:** So, I dug around in the source code a little I think dj-rest-auth does not implement support for `ACCOUNT_EMAIL_VERIFICATION`. Django allauth seems to perform the check in the `LoginView` which is not used by `dj-rest-auth` since `authenticate` is called directly. I could have sworn that `ACCOUNT_EMAIL_VERIFICATION` worked in a previous project, though ...

To fix this, I overwrote the `authenticate` method in the `LoginSerializer`.

**Comment by iMerica** [comment]
Glad you were able to find a solution 👍

**Comment by lchakkei** [comment]
Could you show yours authenticate method in the LoginSerializer plz?

**Comment by florianmartens** [comment]
@lchakkei 

```
class DjAuthLoginSerializer(LoginSerializer):
    
    def authenticate(self, **kwargs):
        """
        Enforce email validation. User can not log in until email is validated
        """
        user = super().authenticate(**kwargs)
        if user.is_admin:
            return user
        primary_mail = EmailAddress.objects.get_primary(user)
        if not primary_mail.verified:
            raise PermissionError("E-Mail address not verified")
        return user
```

**Comment by lchakkei** [comment]
Thx man~
