### ISSUE TITLE
Modified user model

### ISSUE THREAD

**Issue by fessacchiotto** [jazzband/dj-rest-auth#16]
Hi! I've modified the django default user (I've defined a model manager for User model with no username field). I'm getting therefore the following error:

`django.core.exceptions.FieldDoesNotExist: User has no field named 'username'`

Any suggestions on how to proceed? many thanks!

**Comment by bugraaydogar** [comment]
Hi,

I guess you are using email field as username. In this case, please configure following parameters in your settings.py file.

ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USERNAME_REQUIRED = False

I hope it helps,
Bugra

**Comment by fessacchiotto** [comment]
it helped! :-)
