### ISSUE TITLE
dry form submissions

### ISSUE THREAD

**Issue by sumanthratna** [jazzband/dj-rest-auth#163]
It would be nice if there was a `drySubmission` or `validateOnly` input for all the forms that decides whether the DB should be updated. This would be useful for instant feedback/validation (without this, a new account would be created whenever a user edits a field, not when they click submit).

https://github.com/pennersr/django-allauth/issues/2700

**Comment by sumanthratna** [comment]
@iMerica sorry for the ping; what are your thoughts on this? If you agree with this suggestion I'll push a PR soon

**Comment by iMerica** [comment]
I think this is outside of scope and also violates REST principles. When a client makes a request to the endpoints in this package, we assume they're real requests with the intention of authenticating. 

My suggest is to create some validation-specific endpoints if that is something your app requires.

**Comment by sumanthratna** [comment]
> I think this is outside of scope and also violates REST principles. When a client makes a request to the endpoints in this package, we assume they're real requests with the intention of authenticating.
> 
> My suggest is to create some validation-specific endpoints if that is something your app requires.

I see...my personal opinion is that this feature could be pretty useful for SPAs, even if it doesn't strictly abide by REST principles. After all, REST framework wasn't meant to be just for REST APIs; it was meant as a framework for web APIs: https://www.django-rest-framework.org/topics/rest-hypermedia-hateoas/

@iMerica what are your thoughts on a `dj_rest_auth.verification` package that would act similar to the registration endpoints? Or should I create my own package for this?
