### ISSUE TITLE
ImproperlyConfigured registration email verification

### ISSUE THREAD

**Issue by fessacchiotto** [jazzband/dj-rest-auth#17]
hi! when I try to access the following link in the email confirmation sent on user registration: 

`http://localhost:8000/dj-rest-auth/registration/account-confirm-email/MQ:1jIgPr:Ayckd0pouL4B-foYgl2wjdSCYOY/`

I receive the following error:

```
ImproperlyConfigured
TemplateResponseMixin requires either a definition of 'template_name' or an implementation of 'get_template_names()'
```

Where should I create such a template? how should I name the template? it would be great if you could point me to some documentation or shed some light on how to proceed further. cheers!

**Comment by iMerica** [comment]
Hi 👋, thanks for creating this issue. 

It looks like the issue you're describing was recorded in issue [#290](https://github.com/Tivix/django-rest-auth/issues/290) of the upstream project.  

Can you see if any of the workarounds in that issue work for you? If not, I'll investigate a fix.

**Comment by fessacchiotto** [comment]
thanks for your pointer. unfortunately the workaround doesn't work for me... :-(
any help will be appreciated as the user registration is an important part of the process... thank you!

**Comment by anuj9196** [comment]
@fessacchiotto You need to check [endpoints](https://django-rest-auth.readthedocs.io/en/latest/api_endpoints.html) In your case Django is trying to load the template.

You need to make a POST request to the `/rest-auth/registration/verify-email/` with `key` in body.

What I'm doing is create custom adapter to change the verification domain from `Site`, thus user is redirected to frontend.

Then get the key from URL and make POST request to the endpoint.

It's working.

Here is the custom adapter

```
class CustomAccountAdapter(DefaultAccountAdapter):
    def get_email_confirmation_url(self, request, emailconfirmation):
        site = get_current_site(request)
        location = reverse("account_confirm_email", args=[emailconfirmation.key])

        bits = urlsplit(location)
        if not (bits.scheme and bits.netloc):
            uri = '{proto}://{domain}{url}'.format(
                proto=app_settings.DEFAULT_HTTP_PROTOCOL,
                domain=site.domain,
                url=location)
        else:
            uri = location

        return uri
```

**Comment by fessacchiotto** [comment]
hi! thanks for your reply. 
using postman I registered to the system:
<img width="1193" alt="Screenshot 2020-03-30 at 23 39 33" src="https://user-images.githubusercontent.com/97323/77964665-b9480600-72df-11ea-9ddf-c2ffabc6e649.png">
I've received a key (I suppose is the token to authenticate the next api call?)
and then I've received an email:
```
L'Utente maurizio@example.com di example.com ha registrato questo indirizzo e-mail.
Per confermare, clicca qui http://localhost:8000/dj-rest-auth/registration/account-confirm-email/Mg:1jJ1v6:xodPTPjGXR5VPpAapC6ADDFALcg/
```
I've tried to make a post request (with the key in the body), trough postman this time, not the browser, to the endpoint above  found in the mail message but I don't get anything good... 
shouldn't I get some kind of json response to process in my due client? I'm afraid I'm missing something... thanks in advance for your help

**Comment by fessacchiotto** [comment]
I've looked at the source code and read the hint in the url file. I've managed to receive the email link through the vue.js client router and immediately send the call to the confirmation endpoint. thanks for your patience.

**Comment by anuj9196** [comment]
The `key` you are getting while registration is the token key to be used for authentication. May be your email verification setting of `allauth` to set to `OPTIONAL`

You need to send the `key` received in the email addresses for verification.

The endpoint you are using to send verification key is not valid. 

The link received in the email should be routed to the front-end application and from there get the `key` from the URL and make a POST request to `rest-auth/registration/verify-email`

**Comment by aijogja** [comment]
I have fixing this issue by override the `account_confirm_email` url name as mentioned at https://github.com/jazzband/dj-rest-auth/blob/master/dj_rest_auth/registration/urls.py

so in urls.py

```
from allauth.account.views import ConfirmEmailView
...
urlpatterns = [
    ...
    path('confirm-email/<str:key>/', ConfirmEmailView.as_view(),
         name='account_confirm_email'),
]
```

**Comment by Abishek05** [comment]
@iMerica Don't you think there should be a separate API endpoint to verify email address instead of using a template configured from allauth as per #290 you suggested earlier for workarounds? I see there is an API `http://127.0.0.1:8000/accounts/registration/verify-email/` which returns `ok` and doesn't change the verification status.

**Comment by Abishek05** [comment]
> Hi 👋, thanks for creating this issue.
> 
> It looks like the issue you're describing was recorded in issue [#290](https://github.com/Tivix/django-rest-auth/issues/290) of the upstream project.
> 
> Can you see if any of the workarounds in that issue work for you? If not, I'll investigate a fix.

@iMerica Don't you think there should be a separate API endpoint to verify email address instead of using a template configured from allauth as per Tivix#290 you suggested earlier for workarounds? I see there is an API http://127.0.0.1:8000/dj-rest-auth/registration/verify-email/ which returns ok and doesn't change the verification status.

**Comment by lapinvert** [comment]
Why is this closed? We still have the same issue in latest version.

**Comment by jerinpetergeorge** [comment]
I think this issue is related to (or dup of) https://github.com/jazzband/dj-rest-auth/issues/180

**Comment by PeteAndersen** [comment]
This issue is due to django-allauth's default behavior of calling `reverse()`, but another solution to this issue is to change this behavior. I think it is a bit simpler this way if you want the URL in the email to point to your frontend app and/or a different domain than Django is being served.

1. Implement a custom AccountAdapter which overrides the `get_email_confirmation_url()` method. I just hard-coded it.

```python
from allauth.account.adapter import DefaultAccountAdapter

class AccountAdapter(DefaultAccountAdapter):
    def get_email_confirmation_url(self, request, emailconfirmation):
        return f'https://mywebsite.com/register/verify/{emailconfirmation.key}'
```

2. Change the [ACCOUNT_ADAPTER](https://django-allauth.readthedocs.io/en/latest/configuration.html#configuration) allauth setting to point to your custom adapter.

This avoids all of the need for fake URLs and serving HTML views from the API. This also makes it possible to have the email URL be for a different domain than the backend URL, which is not possible with the default allauth behavior.

**Comment by arvandf** [comment]
Definitely need to put together an SPA sample for this project, there are way many custom modifications needed to make it work with react! 
I just had to spend couple of hours for making it work for Google registration before finding this tutorials:
https://medium.com/@pratique/social-login-with-react-and-django-i-c380fe8982e2
https://medium.com/@pratique/social-login-with-react-and-django-i-c380fe8982e2

I'll try to create a repo for the fronted.

**Comment by tarricsookdeo** [comment]
> Definitely need to put together an SPA sample for this project, there are many custom modifications needed to make it work with react! I just had to spend couple of hours for making it work with Google registration before finding this tutorials: https://medium.com/@pratique/social-login-with-react-and-django-i-c380fe8982e2 https://medium.com/@pratique/social-login-with-react-and-django-ii-39b8aa20cd27
> 
> I'll try to create a repo for the fronted.

I know it's been a while but thanks for linking these and saving me a lot of time!

**Comment by duckheada** [comment]
So ant updates on this? the problem still persists...

**Comment by MuhammadAnas47** [comment]
> I have fixing this issue by override the `account_confirm_email` url name as mentioned at https://github.com/jazzband/dj-rest-auth/blob/master/dj_rest_auth/registration/urls.py
> 
> so in urls.py
> 
> ```
> from allauth.account.views import ConfirmEmailView
> ...
> urlpatterns = [
>     ...
>     path('confirm-email/<str:key>/', ConfirmEmailView.as_view(),
>          name='account_confirm_email'),
> ]
> ```

it working for me
