### ISSUE TITLE
New releases is not in the repo

### ISSUE THREAD

**Issue by mohmyo** [jazzband/dj-rest-auth#19]
Why new releases isn't announced here? 

I have installed it when it was at version 0.1.4 and turned on the repo watch releases notifier.
Since then I was tracking repo progress, I loved the way it's being active, didn't see any new releases here but guessed it was waiting for a major one.

Now by coincidence when I was checking my outdated pip packages found out that there was already a new release with version 1.0.0 !! WOW

So, to avoid this I think we need to include new releases here

Thanks.

**Comment by iMerica** [comment]
I've Added 0.1.4 and 1.0.0. Thanks for the notice!

https://github.com/jazzband/dj-rest-auth/releases
