### ISSUE TITLE
Cookies are not added when JWT is used.

### ISSUE THREAD

**Issue by johnvonneumann7** [jazzband/dj-rest-auth#192]
I'm using DRF + React, and I think a token cookie is created when the user logs in, but in the case of React localhost, the Headers contains a Set Cookie, but no cookie is actually created. When I test it, it works fine.

When tested with postman, cookies were generated without any problems.

How can I make sure that a cookie is created even when the login source is localhost?

Or do I need to add it to the cookie on the React side?

※This text has been translated, so please let me know if it is difficult to understand.

**Comment by Luctia** [comment]
Could this be a CORS issue?

**Comment by johnvonneumann7** [comment]
> Could this be a CORS issue?

Probably I agree, but in react, `withCredentials: true` In Django, `CORS_ALLOW_CREDENTIALS = True`.
but the result is the same. How can I solve this problem?

**Comment by johnvonneumann7** [comment]
Sorry, I misplaced the `withCredentials: true` in React. The problem has been solved successfully.
