### ISSUE TITLE
How to determine the login status in React (javascript).

### ISSUE THREAD

**Issue by johnvonneumann7** [jazzband/dj-rest-auth#196]
I want to use React (javascript) to determine login status, but I can't access cookies from javascript due to http-only cookies.

I thought of actually making an HTTP request and using the response status value to determine the status, but I get a 401 error message in the browser developer console.

Should I create a cookie or local storage with the same expiration date and use that value to determine the status?

How can I determine the login status?

**Comment by Luctia** [comment]
I think the method you proposed is fine, but a better way would be to call `/token/verify`. However, as I mentioned in #191 you can't access this endpoint if you use http-only. I guess for now the only option is what you mentioned.
