### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement dj-rest-auth==0.9.5 (demo project setup)

### ISSUE THREAD

**Issue by leni1** [jazzband/dj-rest-auth#2]
Hello.

When I try to install the requirements for the demo project, I get the following error:
```
ERROR: Could not find a version that satisfies the requirement dj-rest-auth==0.9.5 (from -r requirements.pip (line 2)) (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4)
ERROR: No matching distribution found for dj-rest-auth==0.9.5 (from -r requirements.pip (line 2))
```
When I install using `pip install dj-rest-auth`, `pip` installs `dj-rest-auth-0.1.4`. Not sure why this is but thought to bring it to your attention.

Thank you for taking up the maintenance of this project and I'll be happy to open a pull request to fix this.

**Comment by iMerica** [comment]
Thanks @leni1 !

I've updated the version in the demo requirements. It' will install fine now.
