### ISSUE TITLE
Login allowed for user with unverified email

### ISSUE THREAD

**Issue by goodyguts** [jazzband/dj-rest-auth#202]
If, on django-allauth, you set email verification to be mandatory you should not be allowed to login. However, on dj-rest-auth you are able to login using the standard login serializer because the serializer uses django's default authorization function which doesn't check that the user's primary email has been verified. This might introduce hidden vulnerabilities into the websites of people using this library since the registration views check email verification mandatory settings which might make developers assume that the login views are correctly configured.

**Comment by goodyguts** [comment]
I'm happy to write a pull request fixing it if any of the maintainers think that it's worth addressing.

**Comment by iMerica** [comment]
Hi @goodyguts,

Thanks for raising this topic. Currently, Dj-rest-auth's scope of integration with All-auth is a basic registration process. To fulfill that we include a registration view and serializer to cover the happy path. I suggest overriding the serializers included in this package with your own and assigning it in the `REST_AUTH_SERIALIZERS` setting.

For more context: Although this package has an optional registration feature using All-Auth, it doesn't claim to be an extension of all-auth and obey all its configuration flags. So most developers just override the views/serializers in this package with their own to fill any gaps missing.

**Comment by iMerica** [comment]
I'm closing this now, but I'm happy to re-open if we decide to change the level of integration with All Auth in the future.
