### ISSUE TITLE
No reset link in email after customizing PasswordResetSerializer

### ISSUE THREAD

**Issue by lkbhitesh07** [jazzband/dj-rest-auth#206]
I wanted to overwrite the default PasswordResetSerializer so I made CustomPasswordSerializer which looks like this - 

`class CustomPasswordResetSerializer(PasswordResetSerializer):

    def get_email_options(self):
        super().get_email_options()
        return {
            'subject_template_name': 'account/email/password_reset_subject.txt',
            'email_template_name': 'account/password_reset_email.html',
            }`

but from this I got an email somewhat like this - 
![Screenshot from 2021-01-08 20-21-00](https://user-images.githubusercontent.com/44300735/104070400-ca3d8480-522c-11eb-9fd9-85bb61afca96.png)

Here I didn't got the reset link and other items.

So I found a solution in which it was told that put your subject and template file in `templates/registration/` So it will automatically overwrite. I tried that but I got this error

`django_1     | ERROR 2021-01-08 21:59:27,915 log 111 139951641565056 Internal Server Error: /api/auth/password/reset/

django_1     | Traceback (most recent call last):
django_1     |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
django_1     |     response = get_response(request)
django_1     |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
django_1     |     response = self.process_exception_by_middleware(e, request)
django_1     |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
django_1     |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
django_1     |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
django_1     |     return view_func(*args, **kwargs)
django_1     |   File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
django_1     |     return self.dispatch(request, *args, **kwargs)
django_1     |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
django_1     |     response = self.handle_exception(exc)
django_1     |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
django_1     |     self.raise_uncaught_exception(exc)
django_1     |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
django_1     |     raise exc
django_1     |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
django_1     |     response = handler(request, *args, **kwargs)
django_1     |   File "/usr/local/lib/python3.7/site-packages/rest_auth/views.py", line 187, in post
django_1     |     serializer.save()
django_1     |   File "/usr/local/lib/python3.7/site-packages/rest_auth/serializers.py", line 186, in save
django_1     |     self.reset_form.save(**opts)
django_1     |   File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/forms.py", line 311, in save
django_1     |     user_email, html_email_template_name=html_email_template_name,
django_1     |   File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/forms.py", line 249, in send_mail
django_1     |     subject = loader.render_to_string(subject_template_name, context)
django_1     |   File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 61, in render_to_string
django_1     |     template = get_template(template_name, using=using)
django_1     |   File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 19, in get_template
django_1     |     raise TemplateDoesNotExist(template_name, chain=chain)
django_1     | django.template.exceptions.TemplateDoesNotExist: password_reset_subject.txt`

By looking at this error when it calls the save() function of PasswordResetForm it can't find the templates. 

Now to be clear, I'm contributing to an opensource org in which there are several apps and there is no TEMPLATE_DIR mentioned so basically there are defaults folder of templates in apps where it will look but it's not working, please help me out.
Please do let me know if you need any more information.

settings.py file [here](https://github.com/Cloud-CV/EvalAI/blob/master/settings/common.py)

Thanks

**Comment by hamhaingaurav** [comment]
This is more of your template related error, please paste your template code here !

**Comment by lkbhitesh07** [comment]
Hello @hamhaingaurav thanks for replying.
`
{% load i18n %}{% blocktrans with site_name=current_site.name site_domain=current_site.domain %}Hello from {{ site_name }}!

You're receiving this e-mail because you or someone else has requested a password for your user account at {{ site_domain }}.
It can be safely ignored if you did not request a password reset. Click the link below to reset your password.{% endblocktrans %}

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

{% if username %}{% blocktrans %}In case you forgot, your username is {{ username }}.{% endblocktrans %}

{% endif %}{% blocktrans with site_name=current_site.name site_domain=current_site.domain %}Thank you for using {{ site_name }}!
{{ site_domain }}{% endblocktrans %}
`
Here is the template, and also I tried to pass context variable like this 

`'
extra_email_context': {  

                # merge data for all recipients
                'current_site':get_current_site(request),
                'username':user.username
            }`
Here it's giving an error of the request part. Now I'm not getting what to do.
Thanks

**Comment by lkbhitesh07** [comment]
**UPDATE** - It's strange but I solved this issue by simply converting html file to txt. This worked for me.
Thanks
