### ISSUE TITLE
getting error while shifting from "django-rest-auth" to "dj-rest-auth"

### ISSUE THREAD

**Issue by lkbhitesh07** [jazzband/dj-rest-auth#207]
I"m contributing to an open-source project and there I have to shift from "`django-rest-framework`" to "`dj-rest-auth`". So simply I replaced the urls, added `dj_rest_auth` and `dj_rest_auth.registration` to installed apps. But I'm getting this error, not sure what's wrong with it.

error
`
worker_1     | wait-for-it.sh: timeout occurred after waiting 45 seconds for django:8000

worker_1     | Traceback (most recent call last):
worker_1     |   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
worker_1     |     "__main__", mod_spec)
worker_1     |   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
worker_1     |     exec(code, run_globals)
worker_1     |   File "/code/scripts/workers/submission_worker.py", line 42, in <module>
worker_1     |     django.setup()
worker_1     |   File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
worker_1     |     apps.populate(settings.INSTALLED_APPS)
worker_1     |   File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 95, in populate
worker_1     |     "duplicates: %s" % app_config.label)
worker_1     | django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: registration`

Please do let me know what else information will you need.
Thanks in advance.

**Comment by mohmyo** [comment]
Can you share your `INSTALLED_APPS` that you are using at `settings.py`?

**Comment by lkbhitesh07** [comment]
Hello @mohmyo , sorry for not updating, I just got to know that, I didn't remove the `rest_auth` and `rest_auth.registration`.
