### ISSUE TITLE
How to customize Responses?

### ISSUE THREAD

**Issue by bugraaydogar** [jazzband/dj-rest-auth#21]
Hi everyone,

I can be considered new to Django and trying to figure out how I could modify the existing return values of dj-rest-auth. 

One idea might be, creating a custom view by inheriting the existing view but I would like to change all the responses and that option did not sound very clever. Is there any other way that you could recommend ?

Thanks,
Bugra

**Comment by iMerica** [comment]
Generally speaking I think overriding the views and serializers of this project is fine. Thats what I did before dj_rest_auth existed.

If you find yourself overriding lots of views or serializers than maybe it's time to fork the project or propose a way to make dj_rest_auth more extensible.

**Comment by anuj9196** [comment]
The responses are hardcoded in the respective views. As of now there is no way to customize the responses.

But if you want to make slide modifications, it is a good way to extend the view or serializer. I'm doing the same in my application.

**Comment by bugraaydogar** [comment]
Okay, it seems like it is the easiest way to override the view or serializer. Therefore, I'm closing the issue. 

Thanks for the support.
