### ISSUE TITLE
Logout endpoint fails to delete jwt cookie and displays error message

### ISSUE THREAD

**Issue by alichass** [jazzband/dj-rest-auth#212]
Currently the logout endpoint doesn't seems to be wonky in 2 ways:
1. The "Neither cookies nor..." error message is displayed even when jwt cookies (normal or w/ refresh) are set.
2. The endpoint is unsuccessful in removing the existing jwt cookie. As far as I can tell, this is because reponse.logout() is setting different secure/httponly params compared to login - which means the browser doesn't seem to want to delete/remove the existing cookie.

Fixes in pull: https://github.com/jazzband/dj-rest-auth/pull/208

**Comment by iMerica** [comment]
Fixed in #208
