### ISSUE TITLE
custom USER_DETAILS_SERIALIZER breaking

### ISSUE THREAD

**Issue by prtm** [jazzband/dj-rest-auth#30]
While using custom user serializer path in the configuration, it raises error as it expects class
```python3
'str' object is not callable
```
[In this line](https://github.com/jazzband/dj-rest-auth/blob/master/dj_rest_auth/serializers.py#L148)

[Already mentioned in this comment](https://github.com/jazzband/dj-rest-auth/commit/a87a458ccfefd279ba585d4080be3f3aa4a5c1c0#r37899934)

**Comment by iMerica** [comment]
Thanks for raising this issue. I'm going to have a look this weekend.

**Comment by altjohndev** [comment]
I solved locally:

```python
# dj_rest_auth/serializers.py
from django.utils.module_loading import import_string
...
class JWTSerializer(serializers.Serializer):
    ...
    def get_user(self, obj):
        ...
        JWTUserDetailsSerializer = import_string(
            rest_auth_serializers.get(
                "USER_DETAILS_SERIALIZER",
                "dj_rest_auth.serializers.UserDetailsSerializer",
            )
        )
```

I can submit a PR if desired.

**Comment by iMerica** [comment]
Yeah that looks right to me. As long as we don't introduce a dependency on `six` and all tests still pass 👍 .

**Comment by iMerica** [comment]
This has been merged. I'll cut a release once another PR that is pending gets merged.
