### ISSUE TITLE
Simple JWT refresh token endpoint

### ISSUE THREAD

**Issue by soccer99** [jazzband/dj-rest-auth#37]
There is no refresh endpoint that works for simple jwt to return and set the new access token cookie.  I created my own by extending the simple jwt refresh endpoint. If I have time I'll make a PR but wanted to bring it up to the maintainers here that its needed.

**Comment by iMerica** [comment]
Thanks. PRs are welcome 👍 .

**Comment by opeodedeyi** [comment]
Hello, I am sorry if my question is somehow weird as I am not knowledgeable with git. the issue about the token endpoints not being available. with these changes, does this mean it has been fixed? how or when can I access the changes or see them in my project?
