### ISSUE TITLE
State of migrating issues from django-rest-auth to here?

### ISSUE THREAD

**Issue by daredevil82** [jazzband/dj-rest-auth#4]
Firstly, thank you very much for taking this repository on.  Much appreciated.

This might be more a bring-to-Github-higher-up question, but has there been any overtures to the owners of the upstream repository or Github itself to migrate the issues from that repository to here?  One of the values of that repo is the issue tracker and history.  There are apparently 137 open and 238 closed tickets on the upstream repo, and manually duplicating here would be very time-consuming.

**Comment by iMerica** [comment]
Looks like it's a thing that is possible

https://help.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository

**Comment by daredevil82** [comment]
@iMerica I'm not sure that's possible here based on the first two paragraphs of your link:

>To transfer an open issue to another repository, you **must have write permissions on the repository the issue is in and the repository you're transferring the issue to**. For more information, see "Repository permission levels for an organization."

>You can **only transfer issues between repositories owned by the same user or organization account**. You can't transfer an issue from a private repository to a public repository.

Bolded for emphasis.  This means in order for issues to migrate, someone

- needs to have write perms in both [Tivix/django-rest-auth](https://github.com/Tivix/django-rest-auth) and this repo
- AND both repos must be owned by that same person or organization that person belongs to.

Given that these two repos are owned by different organizations, it seems we'd need to raise this up to Github-company level for any action to occur.

**Comment by iMerica** [comment]
The owners of that repo didn't seem receptive about moving it to my org. The next best idea is just to write a script that copies the issue title/content to this project.

**Comment by wadewilliams** [comment]
Not sure if I'll get to helping with this before someone else does, but, it's worth mentioning: 

When copying items from one repo to another, beware of at mentions:

You should likely strip @mentions from the existing description, and add a mention to the author of the issue so they get notified of the movement and can become aware of this fork. 

Also worth referencing the original issue which will drop a reference into the issue on tivix.

Glad you are working on this!

See https://github.com/Tivix/django-rest-auth/issues/610

**Comment by robdox** [comment]
Hello! Wanted to bump this question and ask if any progress has been made here and/or there is another location where you are organizing work which needs to be done? I've been planning to bring the `rest-auth` functionality into my own project and delete the package for a little while until i saw that this effort began. Instead of just rolling my own, I'd love to contribute over here! Not sure what work needs to be done or who is prioritizing what to modernize this so if anyone could point me in that direction that would be great!

**Comment by iMerica** [comment]
Hi @robdox,

I'm not currently working on migrating issues from the old repo to the old one. If theres any particular issue or bug - feel free to open it on this repo.

You're welcome to contribute to this project! Theres probably docs that need improving, additional unit tests, issue triage and bug fixes.
