### ISSUE TITLE
Does using rest-auth effect any of all-auth other functionality?

### ISSUE THREAD

**Issue by Redhaus** [jazzband/dj-rest-auth#45]
Hello, 

Thanks for reviving this project. It is very helpful.
Quick question I see all-auth is a dependency for social auth, which is fine, but I am also using all-auth because of its user invitation feature. Is that something that will still work if I add dj-rest-auth?

If so has that feature been added to the rest auth functionality? Or would that need to still use all auth traditional forms? 

Any insights you can provide would be much appreciated.

**Comment by iMerica** [comment]
Hi @Redhaus 

Invitation endpoints are out of scope (for now) in this package, but I think it is straightforward to add your own views that do invitations.

My advice is to spend a few minutes studying all auth's invitation code (the form code and view code), then port that same business logic to a new DRF API endpoint.

**Comment by iMerica** [comment]
I'm going to close this issue for now.

**Comment by Redhaus** [comment]
Will do. Thanks for the advice and the direction.

Benjamin Read  |  Creative Director  |  Redhaus  |  503.679.1935  |
Redhausdesign.com <http://redhausdesign.com>
