### ISSUE TITLE
Discord Refresh Token and Expiration Date not saved

### ISSUE THREAD

**Issue by ConnorVO** [jazzband/dj-rest-auth#50]
Not sure if this is my fault, a dj-rest-auth problem, or a django-allauth problem, but getting a code from Discord's callback URL and passing it to /dj-rest-auth/discord saves everything properly, except there is no refresh token or expiration date saved in the Social Tokens table.

**Comment by ConnorVO** [comment]
It looks like it is just because in registration/serializers.py the line `social_token = adapter.parse_token({'access_token': access_token})` doesn't include 'expires_in' or 'refresh_token'.

Changing that line to `social_token = adapter.parse_token({'access_token': access_token, 'expires_in': token['expires_in'], 'refresh_token': token['refresh_token']})` worked perfectly (for Discord at least).

Don't have much experience with oAuth, so not sure if that would break other login methods.
        `

**Comment by mimischi** [comment]
I just stumbled upon the same issue, implementing my own OAuth2Provider. Using the solution provided by @ConnorVO works, but I am not sure if subclassing `SocialLoginSerializer` and copy pasting the whole `validate()` method just to update a single line is necessary.

I will create a pull request with the proposed changes, but I am also not sure if this a solution that fits every use case?
