### ISSUE TITLE
JWT Refresh Token for Cookie Authentication

### ISSUE THREAD

**Issue by mattfreire** [jazzband/dj-rest-auth#53]
Hey there

I'm using the JWT Cookie authentication setup and just have a question as to how an access token can be refreshed?

The simplejwt package has an endpoint for refreshing the access token but it's expecting you to pass it the refresh token. But if you're storing the JWT in a cookie then you can't access the refresh token from it, so how do you go about it?

Or am I misunderstanding it completely? If so, please enlighten me!

Thanks

**Comment by mattfreire** [comment]
Forgive me, I've found [a closed pull request](https://github.com/jazzband/dj-rest-auth/issues/37) 

Maybe it's not a bad idea to add this to the docs.

**Comment by opeodedeyi** [comment]
wait, but is this availabel already, or i have to import this manually myself?
