### ISSUE TITLE
Rest-auth :Exlamation mark comes before password

### ISSUE THREAD

**Issue by Pranay9752** [jazzband/dj-rest-auth#56]
I am using rest-auth for authentication. after registration when I try to login it show

{
    "non_field_errors": [
        "Unable to log in with provided credentials."
    ]
}
and when I saw the user on admin panel an an '!' mark comed before password for example password ='!72wlGF0RiGRraz69sveb63FUrebNkAW9xmOoL16C' please help

**Comment by iMerica** [comment]
Hello @Pranay9752, I don't understand your question. Can you try wording it differently? Also can you list the specific steps I can take to reproduce it locally?

**Comment by Pranay9752** [comment]
Thank you. But I figured it out. I had not added hashing mechanism that why that error was coming. Thank you again.
