### ISSUE TITLE
Associating a group or a permission on user registration

### ISSUE THREAD

**Issue by Pinzauti** [jazzband/dj-rest-auth#57]
Is it possible to choose, in the registration endpoint, which group or which permission associate to the user which is being created?
(Related to https://github.com/Tivix/django-rest-auth/issues/587)

**Comment by iMerica** [comment]
Have you looked at doing this in a signal? 

All Auth Signals:
https://django-allauth.readthedocs.io/en/latest/signals.html

Django User Signal:
https://docs.djangoproject.com/en/3.0/ref/signals/

**Comment by iMerica** [comment]
I'm going to close this for now since it's a little out of scope.

**Comment by Pinzauti** [comment]
I'm gonna check, thank you.
