### ISSUE TITLE
How to customize the url in password_reset_confirm.html

### ISSUE THREAD

**Issue by hcgaron** [jazzband/dj-rest-auth#58]
I appreciate you forking and maintaining this project!

I have my api hosted at a different location (completely different url) than my frontend.  When I send the password reset confirm email I'd like to have the url point to one on my front end which can be parsed and displayed there.  I can't figure out where the email content is generated.

I see this line

`    # this url is used to generate email content
    url(r'password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        TemplateView.as_view(template_name="password_reset_confirm.html"),
        name='password_reset_confirm'),`

so I understand that is where the email url is being generated from.  I can't figure out where to customize this email.  I tried searching but forked repos aren't able to search code.  I tried searching the original repo but still couldn't find it.

Thanks!

**Comment by iMerica** [comment]
Override `PASSWORD_RESET_SERIALIZER`, with your own serializer. 

```python
REST_AUTH_SERIALIZERS = {
    'PASSWORD_RESET_SERIALIZER': 'path.to.your.CustomPasswordSerializer'
}
```

make this serializer inherit from the base and add your own custom save method that handles the custom logic.

```python
from dj_rest_auth.registration.serializers import RegisterSerializer

class CustomRegistrationSerializer(RegisterSerializer):
  def save(self, request):
    #  get whatever data you need
    verify_url = ' <add your own custom url here>'
    # send the email using this new verify url
```

See the source code for `RegisterSerializer` [here](https://github.com/jazzband/dj-rest-auth/blob/e73dad7546899373fd790676fc5e29c316eb6452/dj_rest_auth/registration/serializers.py#L166)

**Comment by mohmyo** [comment]
I have been through these questions before, the folks there did a pretty good job to make me understand the full cycle of this, also I have added the code snippet I used in my project.

Please read and check out my past issues
[How to send customized email template for password reset endpoint?](https://github.com/jazzband/dj-rest-auth/issues/9)
[The generated password reset token is not long enough and always having a fixed length](https://github.com/jazzband/dj-rest-auth/issues/22)

**Comment by iMerica** [comment]
Closing this since we now have lots of answers.

**Comment by stfenjobs** [comment]
the code can custom password_reset_confirm url  in  email   ,try


```
from django.contrib.auth import views as auth_views

 urlpatterns += [
    path('password_reset_you_want/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),  
]

```

https://stackoverflow.com/questions/28423959/is-there-a-way-to-change-the-password-reset-confirm-link-sent-by-django
