### ISSUE TITLE
Implementing Registration  info in Docs

### ISSUE THREAD

**Issue by hvitis** [jazzband/dj-rest-auth#61]
I made a clean project, started with implementing this app following the docs but I was fighting a bit with implementing Registration with allauth, since I was getting 500 all the time. 

The error was when I was sending first POST request. App was failing with 500 but user got registered. Each consequent request was returning validation for registered user exist which is OK.

The problem was with setting up the Email for sending the activation link. 
This solved my problem.

`EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
`
Do you think docs should be updated with this info?

**Comment by hvitis** [comment]
I'm still struggling with verifying:
```

    key = self.kwargs['key']
KeyError: 'key'
[08/May/2020 01:46:51] "GET /auth/registration/account-confirm-email/ HTTP/1.1" 500 59
```


    "Templat```
eResponseMixin requires either a definition of "
django.core.exceptions.ImproperlyConfigured: TemplateResponseMixin requires either a definition of 'template_name' or an implementation of 'get_template_names()'
```

**Comment by iMerica** [comment]
Hi @hvitis,

Have a look at this [issue](https://github.com/Tivix/django-rest-auth/issues/290) in the original project

**Comment by iMerica** [comment]
Going to close this since it is a known issue.
