### ISSUE TITLE
PasswordResetConfirmSerializer validations order should be changed

### ISSUE THREAD

**Issue by mohmyo** [jazzband/dj-rest-auth#63]
Hi,

We were integrating our backend with frontend on the password reset part, our frontend dev started to test `password/reset/confirm/` without even making a new password reset request, instead, she used an old and expired token from a dummy example, I was surprised that the feedback from her side was that the password validation error messages are confusing not that the endpoint raised an error that token was not valid.

I dug in [`validate()`](https://github.com/jazzband/dj-rest-auth/blob/a3955bca188ef4475cb4cff9db0c94fcc6313d5b/dj_rest_auth/serializers.py#L208) and found that token validation was the last thing happing on the validation checklist.

I find this very odd, there are so many reasons why token validation should be the first thing to do, for example without even thinking about security and authorization point of view, I can hit `password/reset/confirm/` for hours and keep the server busy to validate my password pair and I don't even have a valid token.

So, I suggest token validation take place before anything else.

Doing it should be easy, just put [this condition](https://github.com/jazzband/dj-rest-auth/blob/a3955bca188ef4475cb4cff9db0c94fcc6313d5b/dj_rest_auth/serializers.py#L225) before anything else, but I thought it's better to discuss it here first

**Comment by mohmyo** [comment]
@iMerica I can help if you want, it should be easy

**Comment by iMerica** [comment]
That would be awesome 👍

**Comment by mohmyo** [comment]
Great, I will be working on it ASAP, be ready for a PR soon.
