### ISSUE TITLE
RemovedInDjango40Warning: django.utils.translation.ugettext_lazy

### ISSUE THREAD

**Issue by seanfarley** [jazzband/dj-rest-auth#70]
Just making an issue so I don't forget, but a heads up that I'm getting this warning in my test suite:

```RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().```

I'm not sure about the backwards compatibility for this project so I'm not positive this is a one-line change. I'd be more than happy to make a PR with some guidance (but feel free to fix yourselves if that's your preference!)

**Comment by iMerica** [comment]
Thank you 👍
