### ISSUE TITLE
Customizing JWT claims 

### ISSUE THREAD

**Issue by alichass** [jazzband/dj-rest-auth#89]
Currently SimpleJWT does not have a simple way of overriding the default `TokenObtainPairSerializer` in its app settings. This makes it somewhat difficult to customize the returned claims in dj-rest-auth without overriding `LoginView` and the `jwt_encode` function. 

I believe a quick fix would be to allow for a new setting in dj-rest-auth, with the default set to `'rest_framework_simplejwt.serializers.TokenObtainPairSerializer'`:
``` python
REST_AUTH_SERIALIZERS = {
    ... ,
    'JWT_TOKEN_OBTAIN_PAIR_SERIALIZER' : 'someapp.serializers.MyTokenObtainPairSerializer',
    ... ,
}
```
with `'someapp.serializers.MyTokenObtainPairSerializer'` defined as in https://django-rest-framework-simplejwt.readthedocs.io/en/latest/customizing_token_claims.html

I think this would then only require the `jwt_encode` function to be changed as such but I am unsure whether this action is better suited to within `app_settings.py`:
```
from app_settings import serializers as appserializers
def jwt_encode(user):
    try:
        from rest_framework_simplejwt.serializers import TokenObtainPairSerializer
        TOPS = import_callable(appserializers.get('JWT_TOKEN_OBTAIN_PAIR_SERIALIZER', TokenObtainPairSerializer))
    except ImportError:
        raise ImportError("rest-framework-simplejwt needs to be installed")

    refresh = TOPS.get_token(user)
    return refresh.access_token, refresh

```

**Comment by iMerica** [comment]
Sounds reasonable to me. Pull requests are welcome 👍

**Comment by iMerica** [comment]
This was merged. Closing now.
